FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY terms.html /usr/share/nginx/html/terms.html
COPY privacy.html /usr/share/nginx/html/privacy.html
COPY docs.html /usr/share/nginx/html/docs.html
COPY nginx.conf /etc/nginx/conf.d/default.conf
